apiVersion: v1
kind: Pod
metadata:
  name: test-pod
  labels:
    app: test-pod
spec:
  containers:
    - name: test-pod
      image: rapa.iptime.org:5000/nginx:sorrymi7
---
apiVersion: v1
kind: Service
metadata:
  name: test-svc
spec:
  selector:
    app: test-pod
  ports:
    - name: nginx
      protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30001
  type: NodePort
